using System;
using System.Collections.Generic;
using Content.Shared._PROX.ProxyControl;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;
using Robust.Shared.Prototypes;

namespace Content.Client._PROX.ProxyControl.UI;

[GenerateTypedNameReferences]
public sealed partial class ProxyControlPodWindow : DefaultWindow
{
    public event Action<NetEntity>? OnProxySelected;

    public ProxyControlPodWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(ProxyControlPodBoundUserInterfaceState state)
    {
        ProxyList.DisposeAllChildren();

        if (state.Proxies.Count == 0)
        {
            ProxyList.AddChild(new Label { Text = Loc.GetString("proxy-control-window-no-proxies") });
            return;
        }

        foreach (var proxy in state.Proxies)
        {
            var hBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(0, 2)
            };

            var labelText = proxy.Name;
            if (!proxy.IsAlive)
                labelText += $" ({Loc.GetString("proxy-control-window-proxy-dead")})";
            else if (proxy.IsOccupied)
                labelText += $" ({Loc.GetString("proxy-control-window-proxy-occupied")})";

            hBox.AddChild(new Label
            {
                Text = labelText,
                HorizontalExpand = true,
                ClipText = true
            });

            var button = new Button
            {
                Text = Loc.GetString("proxy-control-window-select-button"),
                Disabled = !proxy.IsAlive || proxy.IsOccupied
            };

            button.OnPressed += _ => OnProxySelected?.Invoke(proxy.Entity);
            hBox.AddChild(button);

            ProxyList.AddChild(hBox);
        }
    }
}
